### PR TITLE
Dev - Frobot Test 1

### PR DESCRIPTION
**Pull request by talarian1**
- [ ] All [tests](https://github.com/jfrog/jfrog-cli#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----

### CODE REVIEW

**Comment by talarian1** [comment]
The full scan results are available
	Note: no context was provided, so no policy could be determined to scan against.
	You can get a list of custom violations by providing one of the command options: --watches, --repo-path or --project.
	Read more about configuring Xray policies here: https://www.jfrog.com/confluence/display/JFROG/Creating+Xray+Policies+and+Rules
	Below are all vulnerabilities detected.
	Vulnerabilities
	
| SEVERITY | IMPACTED PACKAGE | IMPACTED PACKAGE  VERSION | TYPE | FIXED VERSIONS | COMPONENT | COMPONENT VERSION | CVE |
| --- | --- |  --- | --- |  --- | --- | --- | --- |
| High | github.com/mholt/archiver/v3 | v3.5.1-0.20210618180617-81fac4ba96e4 | Go | | github.com/jfrog/jfrog-client-go github.com/jfrog/jfrog-cli-core/v2 | v1.8.0 |

**Comment by talarian1** [comment]
The full scan results are available
	Note: no context was provided, so no policy could be determined to scan against.
	You can get a list of custom violations by providing one of the command options: --watches, --repo-path or --project.
	Read more about configuring Xray policies here: https://www.jfrog.com/confluence/display/JFROG/Creating+Xray+Policies+and+Rules
	Below are all vulnerabilities detected.
	Vulnerabilities
	
| SEVERITY | IMPACTED PACKAGE | IMPACTED PACKAGE  VERSION | TYPE | FIXED VERSIONS | COMPONENT | COMPONENT VERSION | CVE |
| --- | --- |  --- | --- |  --- | --- | --- | --- |
| High | github.com/mholt/archiver/v3 | v3.5.1-0.20210618180617-81fac4ba96e4 | Go | | github.com/jfrog/jfrog-client-go github.com/jfrog/jfrog-cli-core/v2 | v1.8.0 |

**Comment by talarian1** [comment]
The full scan results are available
	Note: no context was provided, so no policy could be determined to scan against.
	You can get a list of custom violations by providing one of the command options: --watches, --repo-path or --project.
	Read more about configuring Xray policies here: https://www.jfrog.com/confluence/display/JFROG/Creating+Xray+Policies+and+Rules
	Below are all vulnerabilities detected.
	Vulnerabilities
	
| SEVERITY | IMPACTED PACKAGE | IMPACTED PACKAGE  VERSION | TYPE | FIXED VERSIONS | COMPONENT | COMPONENT VERSION | CVE |
| --- | --- |  --- | --- |  --- | --- | --- | --- |
| High | github.com/mholt/archiver/v3 | v3.5.1-0.20210618180617-81fac4ba96e4 | Go | | github.com/jfrog/jfrog-client-go github.com/jfrog/jfrog-cli-core/v2 | v1.8.0 |

**Comment by eyalbe4** [comment]
download

<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The full scan results are available<br style="box-sizing: border-box;">Note: no context was provided, so no policy could be determined to scan against.<br style="box-sizing: border-box;">You can get a list of custom violations by providing one of the command options: --watches, --repo-path or --project.<br style="box-sizing: border-box;">Read more about configuring Xray policies here:<span> </span><a href="https://www.jfrog.com/confluence/display/JFROG/Creating+Xray+Policies+and+Rules" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">https://www.jfrog.com/confluence/display/JFROG/Creating+Xray+Policies+and+Rules</a><br style="box-sizing: border-box;">Below are all vulnerabilities detected.<br style="box-sizing: border-box;">Vulnerabilities</p>

SEVERITY | IMPACTED PACKAGE | IMPACTED PACKAGE VERSION | TYPE | FIXED VERSIONS | COMPONENT | COMPONENT VERSION | CVE
-- | -- | -- | -- | -- | -- | -- | --
High | github.com/mholt/archiver/v3 | v3.5.1-0.20210618180617-81fac4ba96e4 | Go |   | github.com/jfrog/jfrog-client-go github.com/jfrog/jfrog-cli-core/v2 | v1.8.0

**Comment by talarian1** [comment]
test

**Comment by talarian1** [comment]
<img alt="My Image" src="data:image/png;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxAPEBAQDxIQDw8QDw8QEBAPDw8PEBAQFREWFhUS
FRUYHSggGBolGxUVITEhJSkrLi4uFx80OTQsOCgzLisBCgoKDg0OGhAQGi0dHR0tLSsrLSstLS0r
LS0tLS0tLS0tLS0tLS0tLS0tKy0tLS0tLS0tODgtOC04LS0rLS0rLf/AABEIAPsAyQMBIgACEQED
EQH/xAAcAAABBQEBAQAAAAAAAAAAAAAAAQIDBAUGBwj/xAA5EAABAwIEBQIEAwYHAQAAAAABAAIR
AwQFEiExBhNBUWFxkSIyUoFCYqEHFBWxwfAWIzNyktHhU//EABsBAAIDAQEBAAAAAAAAAAAAAAAB
AgMFBAYH/8QAMBEAAgIBAwMDAwIGAwEAAAAAAAECEQMEEiExQVEFE2EiMpGh0QYUQnGBwbHh8CP/
2gAMAwEAAhEDEQA/APXEJULqs4aCEIQiwoIQhKgKBIlQgBqEqVAUNQlQiwoRCVCLChEJUIsKCEqE
iAFSFCVIBqWEJzBJQ2FC0qU+itMYAkGmiJVbbZbFJD8yTMmEpJUaHZXQlhEK4pEQnQiEhjUJ0JIQ
IRCdCIQMahLCIQAiROhLCAGoSwiEANhLCdCRADYSwlhEIsQkISpYQMbCkohMhPplJ9BollISiU1R
ok2LKagpFITYiEsITIiISoQAiEqIQAkISwhACISwhACISoQAiISohACISwiEAIkToRCAESJyoX+M
UKGj3Cew1KjKSjyxSairbLyULnBxhbzHxAd4WzY4lSriabg7x1UY5YS+12QjmhLiLsuJJSBKploi
E5NQIdKJSJUhgiUQhABKJRCIQASiUQiEAEolNTalZjd3NHqQgCSUSo6dVrvlcD6EFSQgAlEohEIA
ESiEh8oAVCZnb9Q9wgOB6j3CAMTirGf3ZmVv+o/bx5Xl99i1Jjs1xVDSTJJMldJxnWLrlw6NECV4
Jj1y+rcVS8kw9wHgArMmvfyuLfEThjj/AJnPJSf0x7HvfDFLDMRGShcl1UfhIg/ZOxXBbjD3iqxx
LQdHN/kV4Dgd9Vt7ijVouLHtqMgtPkaL68ez95sxzBq+iHGehyyrJaeKX0cM682gxOP0Kn2KvD+J
i5oh/wCIaOHlai4PgOq5terS/DBP3Bhd4urBPfBNlemyPJjTfUEJIRCtLzw6x4yvaO1UuH5tV3HB
PGNa8q8mq1vyzmC8nVzDcSq2z89F2R0RPhZUM0ovl8GdDLKL68HuGMcSWtpArPAJ6DUqSxx+1rxy
6rCTrBIBXglzcPquL6ji5xMkkyo2OI1BIPgwrv5t304Lf5l30PpBrgdQQR4Mpy8Ewzie7tiCyo4g
fhcZB8L0Xh39oNCvDK/+U/afwkq+GohL4LoaiEuHwdskSU3hwBaQQdQRsVUxm65NCo8bhpj1VzdK
y5tJWc5xVxOac0qB+Pq/t4XFitcVTu95PaSsriDFeRTfWdq4nQd3FcJT41vmPz06pYQZAAELOW/P
z0Rm48GTWNybqJ6qx9zQIM1GHzMLtuF+JeeeVVgPGzvqWP8Ast4wbjNB9G6Y3n0gMxAEPb0d6qtx
DhpsrkFmjSQ9h7eEPfg+pO13Jz089JUou49z0lZOK8Q0LfQnM76W6rlsV4oqVWhlP4BEOPUlc6SX
amSTuSnm9QiuIchl1naH5OjxDjOq7Sk0NHc6lY1TFbl5+Ko7VVwwBLTCz56vJLucUsmSfWQ51xV3
L3f8ipKWIVgRD36eSkhNy6LnWaXkEmnwxt3cGo8ueS50e652+/Z8MQeXW9RtKudSx/yv9PK36g90
rHFpnUHoR0V+HO4S3Lknhzyw5N/XyM4K/Yw+jXZXvntc2m4ObTZ1I2lepcRYqy2ouAIzFuVrR00X
AMx+5aMoqOjzCzLm/bzAa7nEEyTqdF3fzbyfTjX1M78vqScagqb8nY8CWZ+OuQddBPVdiFz+AcQW
T2Np0qgbAAh3wlb7XA6gyPC0MOL24KJbp4xjBJOx0olCFaX0fNqRKhYhjiJUJEAIUxx29U8lRv1U
4rkieq2X7QLW2pUKTQ58Na1x7d0/HuNra4pGjTzS7qdl5G5WqD/cLvxy33F9yzJqMm2uxo8SYU+7
oGnSEvBzNA/FHReXVqD2OLHNc14MFpBBn0XsGGXWzmmHtgrtMMxWxqOa+7t6ZqtH+oGAz6hcuLIs
VwkXenaqEI+3N14MH9gHDdegK11WY6m2qA2mHAgkd4K6r9otZrnUmCJaHE9xK0r3jChTbFEFxjQA
ZQPsuGv7p1ao6o7dx2Veq1MHDbF3ZdrtTCUNkXdlZgTyE1u6kWVJ0zJXQY0KQJrxCXNsk+eRqkLB
+6dCAngKtk0iEslNc06+isqMhNSE4kHLkKC8tg9sHfur4amFndWQyuMrXYTgchWBpOgnKRsZgraw
HjWvauAL+ZT6tcZ08KjxVY5m8xu7d/RckvUabMs2NS/JZhhX1J0fReE8ZWdwwO5jWHq1xAIK0P47
a/8A2pf82r5lDiNifdP5rvqPuVdtNFZuOTWQkSrCOAEAShLTqFpkIAY7RQuV+s0VBLNHdu6oVAQY
OkKeLkTECdTdBTJSyrk6dkWrGPxB7XywxH6rYsuItQ1zZJ00XP3LdfVWcEpZqzPBldmbHjyY98lf
BY8cNt0d4yDB8SpD7JjDonkyvMPqc66DGnupGprRG6Rx1Q+egdAc0fdMc3UJXO1lNLlONkXQ+nPV
TM2VVj1KH7qM4scWWEia13dKSqaotHBNcUhcEmaUJCsrXVMPa5p6grzy5p5Xub2JXpDzquDx1kV3
+TK3PSpu5R+LJYX9TRnpISoW0dBsShIClWTqcKxT2o5ouxU0lJKQqiiQgdBBG6tB7Koh3wv6Huqj
lGp7bAfVpFpgpgKt0q4eMlT7O7KCtQLDrsdipKXaXUGitcNkeiucMNBregKgOoUmBnJcNB03H6rp
Um8M4/A2/oaO0cVJTfAPdQEozLDcbRyKRYB2Tp/RQU3ap7z2VbhzRJS4sc/VRuQ4lRvdp5U4xE2I
4xslFWITHv7qNz9ZVyha5RW3XQuBxIStqR/6qramu6V1QSoey+hLeWmukp+gUFN+kwmPrdFX7bbp
die6lZLUA69Vw2PEc50LsqlTQ+i4S/qZqjz5K1PTINSbfgsw8zsgQmPfCZzQto7NrNsFI12qjlCt
y4o5Y7ZHGlRLKa5yaXQoRdM76rGyaWeOVVZYk30JpTSUzOCHZTrCSg6WglL2mlY3F1Y9Xbe5BGSp
qOh6hUpQoyipcMimT3FuWnu07FU3VclRr/IV+1uPwO1af0UGKWUNMajcFPBPbPbLuTjVnW0qmZjX
DqAQnZhC5/hjEMzOUTq3aey2XdVzTw7JOLOHLFwk0S54lKK5VaUoR7S7lW5lp1XTyoqtcNGYmGgS
VFKHa6HUdkliSJbvIyjfUqurHBw8FPc5Yl1gLc2ei51F+/w7H7KP90vojnN/3ayuiOJLlfqXPFjl
zGdf36/9mtdXzKLS55A/qqODPq1Hur1Ja12jGfl6FQW+BgvD67zVcNgflB9FtDsFY4LngJShji4w
dt9X+37lwVNBGqZzNVC1/QJfPZczxJFFshxS65dJx6kQFyXKJaXzstXFbgVjlaYy/qs94yUnA7rT
0uH24fLNTTYnGNvuZ1cqNOY3MQOpVn+Hu7hdfQ6kqRooQhdBnCKvcWYdqNCrKEmrJRk4u0VMNo5a
oDxLToVb4gpNphjWSJ1VrDqeZ4npqjE3Bz+4GgVbhzR0LM6to59r39JVq3ZUO5geVbAQj2YvryVy
y30RSqXbmGCJhXbPFA4cp4gO2PYqG7t840+YLLLSDGxlc+XS432LcahNfJbfntqsjcGQe4XWWN62
s0OG/X1VOlh4qtpuqiXBsfor1Gk1ghoAHiVk6jXQ4TVtdzYwfw3m12JzclFrjnrfyShyWUn9/wB6
on+9E8ebHk+3qYOt9H1ejf8A9YceVyvz+4oclBSICt2pmWDkSkLkJxjSGCEKOrWawEuIAHdSYVZI
sXGsWDQabDJ6lWcTrl1satMwNvVciTOpXRjwdHJHfptN/VP8Ejqx32Wk2m+rQc6Jy7lZC6nAjNnV
HbN/JdaVmg3tXBz+G0i+q1oXRfuDu49liYAP89voV1nNKiyRgIQhdJmAhCEAXcPrtZmJ36Ko8ySe
5TUJJBfFAhCEwETqVsKj2iJJI1T6FLO4D3W1SpNYNAs3X66OBbOsmb3ovo+XWS9y9sYvr5a7Is17
Z9PRzSP5bKJXbfE6jND8bdsrtREKXLQq7HlPPQ/KvKSbVJnutFJJ5ZrlOb5rjhJfgzUsqzc2D2dM
zejm6hVVFPujRTU15TCUgeDoDsqd7cZfhG5/RVqRcwgxofVaOmyzX3O0ea9W/hvSaiDliShkf29k
34o11BXrBu89E6lVDhIUV4yQDGzo+2q0Mkns3RPCel6XHLXx0+qi0m2mulOuP1Ma54gdJDGx5Kyb
m7fUMuJK6C9wdtUB7NHFo9Csl2DVh+Fd2KeNxTQ4rFik49HFtO+vHBMzFW/uhoQc0nXpusgK/wDw
et9P8012E1gJyq95IvuWLJj7NfkpLawPEqdKnVY+fiBj2WO5pBgiD5SKSdck2rNPh5mavI2EldDn
XL4Xe8h+aJBEQr38bH0lIZ2DeE+pd9k48Jdn6+i600Xdj7I5TtoPsqfffkytrOQ/wiZMv/RJ/hM6
fHvv4XYcp3Y+yTlu7H2T95+Qo5FvCP5//UHhHs/00XX8s9j7I5Z7H2R7z8hTOQ/wj+f10TRwkY+b
7LsOW7sfYo5bux9ke8/IUzh6+F/uzonNLQZ902Vv4nWoVHZHktc38Q266LNq4c4CWEPH5d/ZeY1u
VT1Em3Z9Q9GhLH6dDH9kmnV/LfJSnT1Qlc0jQiD5SLmbt2a+mwRwYo449v18v/LJqF29h+Fx9DqF
NcX1Fwmo3I76mbeypErJvK2Y+ApQx72W+2pO+5PWszzG65mvIId4lbD7AZMsT8MLPwo8wZDu05me
NtFuF8DXULpUpR4PB/xdqZLUYoRnzDnjqn2f7HOlrqL4IIbPnv8A+K22HDwVddf0CcrtfsHLVtbS
2e5jA6GOgnoVfi1Lhw1wZnq856mGPLmxPHl4+rop/PmzOw7AXloOeWkSPHhWjgTvqC36Voxgijmd
T3BMrSGEuNHmA6/THRaTyY1GLlxfBivDPJKTatrlv/ZwowitMRp3VS/oOoML6gho0Hlem3TWm3ZD
YcNNtVxvFrwy3LXNzOeQ1gI6lGOcZxbqqdE46SPuxh1uunycULBt4Q6mIJ0ICu0+CCdXPiNTouq4
cwMW9JvwnOQC4kbE9Fs8t3Y+xXRCbSqwm3CTjC9qfB5w3gxzgSCdD8IIAnypf8E1PqHsvQuU7sfY
o5bux9ipe58kfcmdxyG9h7INBvYeylQvGb2er2R8Ig5LfpHsEcpv0j2UpCMqe5+RqMPCIeU36R7J
eU36R7KWEsI3PyG2PhEPLb9I9gsvie7FvbPe0CYgad1sqjjOHC5oupHSRoexRuZZhWNZIuS4tWeM
1HFxJO5MlPpVnMMtJB8FaGKYBcW5Icwlo2cBIhZan1PbwnGcbi7ReZiAdIqsD56jRyV1pSeJpP1+
l+ioKKvVyCfZLb4F7dfbwR4qHU/hIInr0WWFeoXBqzTqEnN8pPQqBtCCQ7odVq6DSyzZFhXV9f7e
Tn1+vhodPLNk6rp8vsixZ1DSOYdpPkK7bmpcVG5g4US6HESBCohs6d9F21ha/utBjLkDI5wIy6GC
tz1zR4scMbhw/tru+/6f7Pm3pnqdZsufLFSyPlSfSP8A7ojnbnDGUqhaw59dCYVt9maLqZqSGOiS
3t1C7+lw/btLHMAfmgiZKvY1hNOtSDMg8RoR6LzsNXGLSr+5PUaXU6tvLnybpf08tpfHj8FjCTRd
RZycpYGgDafurwA2jRcpwlhde1fVFRxFMbDofK6um8OAI1B2XFmiozdO0dumnvgt0dr8Bkb2HsuB
u3DEMWZSABoWgzOgaF/Rdhj+IC1t6tZ34WGPJ6LD/Z3hxZQdcPH+bcuNR07gdAp4nthKf+EdKSXJ
1PLb9I9gl5bew9gnKF9YBwbErnI7V4JOW3sPYI5bew9k5GiOfkNq8DkJEsqIgSJCVC67YPxBAE6F
Wp3rHGBqU64uQyJ3PROh0ToWecSE6DZMOK/lT2se1mi9gcIIBHYiVz2L8I29eXNHLf3bt7LQ/iv5
UNxOeiNrLMc8mJ3BtM89xbhG4oSWjmM7t39lzGIWjogggjoRC9oOKflTG21G4kuotPcwFOLlF2bG
H1mcVWWN/K4PE8HwevdVAyi05pkE6AfdbjuEL4GDSJPeQvW7Wzo0IbTY1mb6QJWXxNxCLQBjRmqv
+UdvK1dB6pmwTaxQTcvJhev6iOuSlkbhCHRfL/34OYwbhFtuRVuiC8atpjv5VHGbl95cCmwaNOUR
t6q3f3dWmwuec9StsPpnstvhLAhTGd+rnak9vCs1GryTbz5nufSPj/HwYkcCnWngqXWfn4RuYPam
lSbmM5WjdW6BzkuO2zVFd1AYptI13joFapNAAA6LEk2+X3NtJJUjG4wvX0LZzmbn4T91BwNfGrbA
O1LCRJ6qbjKgX2jwAXEawFxnBmLut6nKyF3McBHYrtxYvc0zpcpmTn1HtayO5/S1RrcdvddXFth9
M6PcKlWOjQZgrt7eiKbGsbs1oA+yoUMGosruuQ0854ALiSYHYLTC5ck04xiu3/Pc1rILt5DdEjGA
hrjuFM7yoKT8xJ2aNB/2qrAnedNVR5P5ipQ81HafI3fyVZyjwndDsgu7kMb56BRYe5zgXOO+3oqO
Z1R4cRLZ+0Ka/ugBkZ9067DrsNxC8zfC3bqe6oIT7dmY67bn0VqVE6ovWQFNhe7c7KrXeXGT8x/Q
KWvVmDHwjRo/qodR/uKiutkV5GR0H3SPHZOf8Ijqd1GpEhAFNUZlEdeqls6WhqHZu3kqLI58uO3d
KwIity0aGU9dNJKzqLeY5oiI38q7dguIY3bqoTd8EZPsJZuNR7nnYaBZ/EOH0qzmkiardo/qtkBt
NvgfqqNvSc5+f2lEZOL3LiiuUYzVSVo46nhlb94mq05W6sG8rrKTnhmTYk7jt5WjUpiQd3DY9k3k
CDm3OpVmTP7lWuhTgwLFdO7dmeLciDOuqltGuLhvG51Vo0ARpupaFOJVTlwdG4fUiDO3WVm21jRN
XmNY0FuxAjXurF49xHw7SlDsjfJ1KItroQcYvqrJTVl2Vv38JbisGCfZQWNPcxHnv5UN3UMl306A
JJKyVFV948mJSPuTGUHTZQxu46Jzbd2XPGitpFnBZt6rpDQD6f1V/lu/sqrQaWNzHV7tGhO5VTuo
PqQZXo1XMBaQfB7KuW9/ddCWDsmVKLT0CSmPcYPLhTWlDNM7DcrQqUm9k0aM001TcgcuCBlKZc75
W/KEopx8ZGp28KzU+Zg6Tsozq70KVisp1KEmfvKYy3LjAWhHTpKdaD4nJ7h7uCOpbyAwGAN/KhuG
nRrR8PTytAfKfuqtP5gfVRTIpi4dQIknrp6K1AB01P8AIKSnsmt2SbsHyVq8k6zlUx/L208JzuiQ
IsVhTGmuhRlndPSpB1EhIZ6aKRMKAZENT4H6lR1Kcknpp9wp3bfdRj/tMZI4aQNP+lVqNky3Udla
dsmDRw9EJgZ9S32kaA6BWLfUFv4B/cK3UaCU5ghPcFlUg6vgzs0dvKrRW7FaqVClQ0z/2Q==" />

**Comment by talarian1** [comment]
test

**Comment by talarian1** [comment]
SEVERITY | IMPACTED PACKAGE | IMPACTED PACKAGE VERSION | FIXED VERSIONS | COMPONENT | COMPONENT VERSION | CVE
-- | -- | -- | -- | -- | -- | --
 | github.com/mholt/archiver/v3 | v3.5.1-0.20210618180617-81fac4ba96e4 |   | github.com/jfrog/jfrog-client-go github.com/jfrog/jfrog-cli-core/v2 | v1.8.0

**Comment by yahavi** [comment]
SEVERITY | IMPACTED PACKAGE | IMPACTED PACKAGE VERSION | FIXED VERSIONS | COMPONENT | COMPONENT VERSION | CVE
:--: | -- | -- | -- | -- | :--: | --
 High | [github.com/mholt/archiver/v3](http://github.com/mholt/archiver/v3) | v3.5.1-0.20210618180617-81fac4ba96e4 |   | [github.com/jfrog/jfrog-client-go](http://github.com/jfrog/jfrog-client-go) [github.com/jfrog/jfrog-cli-core/v2](http://github.com/jfrog/jfrog-cli-core/v2) | v1.8.0

**Pull request closed without merging**
